config_version: "1.0.0"
repo:
  url: "https://github.com/jhy/jsoup"
  branch: "master"

execution_plan:
  mode: "tests"
  ignore_failures: true
  test_command: "mvn surefire:test"
  granularity: "commits"
  num_commits: 500
  num_runs: 30
  num_repeats: 1
  newest_commit: "3a767deb3fad99bc91cadf799e726dea29de042d"
  randomize_tasks: true
  batch_size: 100
  compile_commands:
    - "mvn clean test-compile"
    - "mvn test"

limits:
  temperature_safe_limit: 65000
  energy_regression_percent: 20

tracked_file_extensions:
  - "java"
  - "xml"
  - "properties"
  - "yaml"
  - "yml"

cpu_thermal_file: "/sys/class/thermal/thermal_zone0/temp"

regression_detection:
  min_commits_before: 0
